name: CI/CD Pipeline using GHCR

on:
  push:

env:
  IMAGE_NAME: food_lens
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  mypy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python and PDM
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install PDM
        run: python -m pip install pdm
      - name: Install dependencies and run mypy
        run: |
          pdm install --group=mypy
          make mypy-ci

  ruff:
    name: Run ruff
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python and PDM
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install PDM
        run: python -m pip install pdm
      - name: Install dependencies and run ruff
        run: |
          pdm install --group=ruff
          make ruff-ci
  test:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python and PDM
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install PDM
        run: python -m pip install pdm
      - name: Install dependencies and run tests
        run: |
          pdm install --group=test-ci
          make test
