name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker run --rm -d --name food_lens \
              -e API_TOKEN=${{ secrets.API_TOKEN }} \
              -e SECRET_TOKEN=${{ secrets.SECRET_TOKEN }} \
              -e WEBHOOK_URL=${{ secrets.WEBHOOK_URL }} \
              -e WEBHOOK_ENDPOINT=${{ secrets.WEBHOOK_ENDPOINT }} \
              -e UPDATING_METHOD=${{ secrets.UPDATING_METHOD }} \
              food_lens:${{ github.sha }}
