name: Deploy stage

on:
  workflow_dispatch:

env:
  IMAGE_NAME: food_lens
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Log in to GHCR"
            echo ${{ secrets.GHCR_PAT }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            
            echo "Pulling the Docker image"
            docker pull--rm  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            
            echo "Deleting old container"
            docker stop ${{ env.IMAGE_NAME }} || true
            docker rm ${{ env.IMAGE_NAME }} || true
            
            echo "Starting new container"
            docker run -d --name ${{ env.IMAGE_NAME }} \
              --network shared-network \
              --restart on-failure \
              -e API_TOKEN=${{ secrets.API_TOKEN }} \
              -e SECRET_TOKEN=${{ secrets.SECRET_TOKEN }} \
              -e WEBHOOK_URL=${{ secrets.WEBHOOK_URL }} \
              -e WEBHOOK_ENDPOINT=${{ secrets.WEBHOOK_ENDPOINT }} \
              -e UPDATING_METHOD=${{ secrets.UPDATING_METHOD }} \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
