name: CI/CD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . -t food_lens:${{ github.sha }}

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python and PDM
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install PDM
        run: python -m pip install pdm
      - name: Install dependencies and run tests
        run: |
          pdm install --group=test
          make test

  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python and PDM
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install PDM
        run: python -m pip install pdm
      - name: Install dependencies and run linters
        run: |
          pdm install --group=lint
          make lint

  deploy:
    name: Deploy to Server
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
      - test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull food_lens:${{ github.sha }}
            # docker run --rm -d --name myapp myapp:${{ github.sha }}
